Feature/question area
nantonov/AIS pull request #30
Opened 2021-10-21 14:40 UTC by VadimZharikov

2021-10-21 15:22 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionSetController.cs
> +    [Route("api/[controller]")]
We have const for this route.

2021-10-21 15:23 UTC, PaShkadun commented on AIS/AIS.API/Controllers/TrueAnswersController.cs
> +                );
Do it like in method in bottom.

2021-10-29 14:35 UTC, PaShkadun submitted a review, later dismissed

2021-11-01 08:58 UTC, PaShkadun approved these changes

2021-11-01 10:21 UTC, Blackolf931 requested changes

2021-11-01 10:21 UTC, Blackolf931 commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +            var Question = _mapper.Map<Question, QuestionViewModel>(await _questionService.GetById(id, ct));
you can make it easier "_mapper.Map<'QuestionViewModel'>"(param)

2021-11-01 10:21 UTC, Blackolf931 commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswer, TrueAnswerViewModel>().ReverseMap();
Do you really need it? (ReverseMap())

2021-11-01 10:21 UTC, Blackolf931 commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswer, TrueAnswerAddViewModel>().ReverseMap();
The same

2021-11-01 10:27 UTC, PaShkadun requested changes

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionAreaController.cs
> +            var questionArea = _mapper.Map<QuestionArea, QuestionAreaViewModel>(await _questionAreaService.GetById(id, ct));
You can do it easy (mapping).

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionAreaController.cs
> +        public async Task<QuestionAreaViewModel> UpdateQuestionArea(QuestionAreaViewModel questionArea, CancellationToken ct)
You need use short model in parameters.

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionSetController.cs
> +            var questionSet = _mapper.Map<QuestionSet, QuestionSetViewModel>(await _questionSetService.GetById(id, ct));
Do it easy.

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionSetController.cs
> +        public async Task<QuestionSetViewModel> UpdateQuestionSet(QuestionSetAddViewModel questionSet, CancellationToken ct)
Is it addViewModel in update method?

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +            var Question = _mapper.Map<Question, QuestionViewModel>(await _questionService.GetById(id, ct));
Do it easy.

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +        public async Task<QuestionViewModel> UpdateQuestion(QuestionViewModel Question, CancellationToken ct)
Short model.

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/TrueAnswersController.cs
> +            var trueAnswer = _mapper.Map<TrueAnswer, TrueAnswerViewModel>(await _trueAnswerService.GetById(id, ct));
Do it easy.

2021-11-01 10:27 UTC, PaShkadun commented on AIS/AIS.API/Controllers/TrueAnswersController.cs
> +        public async Task<TrueAnswerViewModel> UpdateTrueAnswer(TrueAnswerViewModel trueAnswer, CancellationToken ct)
Short model.

2021-11-01 11:30 UTC, PaShkadun requested changes

2021-11-01 11:30 UTC, PaShkadun commented on AIS/AIS.API.Tests/Controllers/EmployeeControllerTests.cs
> +            Assert.Equal(inputEmployeeViewModel.CompanyId, result.CompanyId);
Why did you delete shouldly and did it with Assert?

2021-11-01 11:30 UTC, PaShkadun commented on AIS/AIS.DAL/Repositories/IntervieweeRepository.cs
> +        protected override IQueryable<IntervieweeEntity> Query(bool eager = false)
Why? Is it necessary in this repository? It doesn't use.

2021-11-01 11:30 UTC, PaShkadun commented on AIS/AIS.API.Tests/Controllers/EmployeeControllerTests.cs
> +            Assert.Equal(inputEmployeeViewModel.Name, result.Name);
The same.

2021-11-01 11:47 UTC, Blackolf931 requested changes

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API.Tests/Controllers/EmployeeControllerTests.cs
>  }
Why you change this file?

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +            var Questions = await _questionService.Get(ct);
![image](https://user-images.githubusercontent.com/52563506/139665860-634afbc3-8511-4f6c-b565-981668d6184d.png)

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +        public async Task<QuestionViewModel> AddQuestion(QuestionAddViewModel Question, CancellationToken ct)
Question => question

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/Controllers/QuestionsController.cs
> +        public async Task<QuestionViewModel> UpdateQuestion(QuestionUpdateViewModel Question, CancellationToken ct)
The same

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/ViewModels/QuestionArea/QuestionAreaUpdateViewModel.cs
> +        public int Id { get; set; }
We don't use Id prop this

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/ViewModels/QuestionSet/QuestionSetUpdateViewModel.cs
> +        public int Id { get; set; }
The same

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API/ViewModels/TrueAnswer/TrueAnswerUpdateViewModel.cs
> +        public int Id { get; set; }
The same

2021-11-01 11:47 UTC, Blackolf931 commented on AIS/AIS.API.Tests/Controllers/EmployeeControllerTests.cs
>  }
Maybe you copy this file from main

2021-11-01 13:41 UTC, VadimZharikov commented on AIS/AIS.DAL/Repositories/IntervieweeRepository.cs
> +        protected override IQueryable<IntervieweeEntity> Query(bool eager = false)
Check the base class

2021-11-01 14:03 UTC, VadimZharikov commented on AIS/AIS.API.Tests/Controllers/EmployeeControllerTests.cs
>  }
methods support async implementation

2021-11-02 07:38 UTC, nantonov requested changes

2021-11-02 08:22 UTC, PaShkadun commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswer, TrueAnswerViewModel>().ReverseMap();
Why?

2021-11-02 08:22 UTC, PaShkadun commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswerUpdateViewModel, TrueAnswer>().ReverseMap();
Why?

2021-11-02 08:25 UTC, VadimZharikov commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswer, TrueAnswerViewModel>().ReverseMap();
to map navigational properties dependencies

2021-11-02 08:25 UTC, VadimZharikov commented on AIS/AIS.API/Mapper/MappingProfile.cs
> +            CreateMap<TrueAnswerUpdateViewModel, TrueAnswer>().ReverseMap();
to map navigational properties dependencies

2021-11-02 08:49 UTC, PaShkadun approved these changes

2021-11-02 08:49 UTC, Blackolf931 approved these changes

2021-11-02 08:58 UTC, nantonov approved these changes

2021-11-02 08:58 UTC, merged