QuestionIntervieweeAnswerEntity were updated.
nantonov/AIS pull request #37
Opened 2022-02-16 14:44 UTC by CrazyKamenwik

SessionId and QuestionSetId were added.

2022-02-16 14:46 UTC, hromau approved these changes

2022-02-17 06:59 UTC, GagarinPavel requested changes

2022-02-17 06:59 UTC, GagarinPavel commented on AIS/AIS.DAL/Entities/QuestionIntervieweeAnswerEntity.cs
> +        public int QuestionSetId { get; set; }
unnecessary to link to QuestionSet

2022-02-17 06:59 UTC, GagarinPavel commented on AIS/AIS.DAL/Entities/QuestionIntervieweeAnswerEntity.cs
>          public int QuestionId { get; set; }
add public virtual SessionEntity Session { get; set; }
and change SessionEntity ( add public virtual ICollection< QuestionIntervieweeAnswerEntity > QuestionIntervieweeAnswers { get; set; } )

2022-02-17 07:23 UTC, GagarinPavel commented on AIS/AIS.DAL/Entities/QuestionIntervieweeAnswerEntity.cs
>          public int QuestionId { get; set; }
and update models on API and BLL layers

2022-02-17 11:14 UTC, nantonov requested changes

2022-02-17 11:14 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
Strange migration

2022-02-17 11:29 UTC, stas1408123 approved these changes

2022-02-17 11:31 UTC, CrazyKamenwik commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
What exactly? Naming?

2022-02-17 11:44 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
Content of the migration :)

2022-02-17 11:49 UTC, CrazyKamenwik commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
It is what it is)

2022-02-17 12:04 UTC, nantonov requested changes

2022-02-17 12:04 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
You added Session Id- ok, but why in the migration we delete QuestionSetId

2022-02-17 12:20 UTC, CrazyKamenwik commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
Because the first task was "add SessionId and QuestionSetId into QuestionIntervieweeAnswerEntity", but later Pavel said that there is no need to add link to the QuestionSet, that's why I deleted it.

2022-02-17 12:31 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +    public partial class Update_SessionEntity_and_QuestionIntervieweeAnswerEntity : Migration
Where you find that QuestionSetId is exist? In this case we can delete field "ABC" because I guess that it exists and 100 more fields

2022-02-20 19:57 UTC, nantonov requested changes

2022-02-20 19:57 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +            migrationBuilder.DropColumn(
Why it still here?

2022-02-22 08:28 UTC, nantonov requested changes

2022-02-22 08:28 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +            migrationBuilder.AddColumn<int>(
Why it here?

2022-02-22 08:28 UTC, nantonov commented on AIS/AIS.DAL/Migrations/20220217091244_Update_SessionEntity_and_QuestionIntervieweeAnswerEntity.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Where adding the SeesionId column?

2022-02-22 14:41 UTC, nantonov approved these changes

2022-02-22 15:28 UTC, closed without merging