Feature/random next question
nantonov/AIS pull request #50
Opened 2022-02-23 10:55 UTC by GagarinPavel

2022-02-23 11:25 UTC, nantonov requested changes

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.API/Controllers/NextQuestionController.cs
> +        public async Task<QuestionViewModel> next(int sessionId, int setId, CancellationToken ct)
Should starts from upper letter

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.BLL/Interfaces/Services/INextQuestionService.cs
> +        Task<Question> next(int sessionId, int setId, CancellationToken ct);
Should starts from upper letter

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.API/Controllers/NextQuestionController.cs
> +        public async Task<QuestionViewModel> next(int sessionId, int setId, CancellationToken ct)
FE doesn't know about question set, it should be handled internally

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.BLL/Constants/EmptyQuestion.cs
> +        public static Question Empty = new() { Id = -1000};
For what?

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.BLL/Services/NextQuestionService.cs
> +            return EmptyQuestion.Empty;
You can return null, it will mean that there are no more questions

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.BLL/Services/NextQuestionService.cs
> +            List<QuestionEntity> questions = (await _questions.Get(ct)).Where(item=> item.QuestionSetId == setId).ToList();
Extend GenericRepository to use filters

2022-02-23 11:25 UTC, nantonov commented on AIS/AIS.BLL/Services/NextQuestionService.cs
> +        public async Task<Question> next(int sessionId, int setId, CancellationToken ct)
We should determine which is next question by sessionId, internally on BE side

2022-02-24 08:17 UTC, Blackolf931 approved these changes

2022-02-25 11:36 UTC, nantonov approved these changes

2022-02-25 11:39 UTC, CrazyKamenwik approved these changes

2022-02-25 12:19 UTC, merged