Feature/update database
nantonov/AIS pull request #54
Opened 2022-02-28 12:09 UTC by GagarinPavel

2022-02-28 20:17 UTC, nantonov requested changes

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.API/ViewModels/QuestionAreasQuestionSets/QuestionAreasQuestionSets.cs
> +    public class QuestionAreasQuestionSets
Add ViewModel postfix please

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.API/ViewModels/QuestionAreasQuestionSets/QuestionAreasQuestionSets.cs
> +        public virtual ShortQuestionSetViewModel QuestionSet { get; set; }
not needed virtual in vm

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.API/ViewModels/QuestionsQuestionSets/QuestionsQuestionSetsViewModel.cs
> +    public class QuestionsQuestionSets
Add ViewModel postfix please

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.API/ViewModels/QuestionsQuestionSets/QuestionsQuestionSetsViewModel.cs
> +}
format the file please

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.BLL/Models/Question.cs
> +        public virtual IEnumerable<QuestionSet> QuestionSets { get; set; }
No needed virtual here

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.BLL/Models/QuestionsQuestionSets.cs
> +}
format please

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.BLL/Models/QuestionsQuestionSets.cs
> +    public class QuestionsQuestionSets
No needed virtuals in this file

2022-02-28 20:17 UTC, nantonov commented on AIS/AIS.BLL/Services/NextQuestionService.cs
> +                    if (answers.Count(answer => answer.Question.QuestionSets.Any(s=> s.Id == set.Id)) != set.Questions.Count)
What happens here?

2022-02-28 20:50 UTC, nantonov approved these changes

2022-03-01 05:47 UTC, Blackolf931 approved these changes

2022-03-01 08:36 UTC, stas1408123 approved these changes

2022-03-01 08:36 UTC, merged