Feature/fix delete questions and question area in question set
nantonov/AIS pull request #63
Opened 2022-03-12 07:31 UTC by Blackolf931

2022-03-12 07:35 UTC, GagarinPavel approved these changes

2022-03-12 07:46 UTC, nantonov requested changes
- Get rid of commented code
- Up coverage

2022-03-12 07:46 UTC, nantonov commented on AIS/AIS.BLL/Services/QuestionsQuestionSetsService.cs
> +        public async Task Delete(int questionSetId, int questionId, CancellationToken ct)
just return?

2022-03-12 14:26 UTC, hromau approved these changes

2022-03-13 08:38 UTC, nantonov approved these changes

2022-03-14 07:14 UTC, merged