Feature/add question set add
nantonov/AIS pull request #66
Opened 2022-03-18 09:04 UTC by Blackolf931

2022-03-18 09:12 UTC, GagarinPavel approved these changes

2022-03-18 09:24 UTC, stas1408123 approved these changes

2022-03-18 09:24 UTC, stas1408123 approved these changes

2022-03-18 09:25 UTC, nantonov requested changes
Fix smell code from sonar

2022-03-18 09:33 UTC, nantonov requested changes

2022-03-18 09:33 UTC, nantonov commented on AIS/AIS.API/ViewModels/QuestionSet/QuestionSetAddViewModel.cs
> +#nullable enable
add disable too

2022-03-18 09:33 UTC, nantonov commented on AIS/AIS.BLL/Interfaces/Services/IQuestionSetService.cs
> +        Task<QuestionSet> Add(QuestionSet entity, CancellationToken ct);
'IQuestionSetService.Add(QuestionSet, CancellationToken)' hides inherited member 'IGenericService<QuestionSet>.Add(QuestionSet, CancellationToken)'. Use the new keyword if hiding was intended.

2022-03-18 09:33 UTC, nantonov commented on AIS/AIS.BLL/Models/QuestionSet.cs
> +#nullable enable
Use disable too

2022-03-18 09:33 UTC, nantonov commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +        private static List<int> ConvertToList(QuestionSet entity)
Why we cannot use ToList() or smth like that?

2022-03-18 09:33 UTC, nantonov commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +            questionAreaIds.ForEach(x => _questionAreasQuestionSetsRepository.Add(
Just create an entity and save it once

2022-03-18 09:37 UTC, hromau approved these changes

2022-03-18 11:13 UTC, Blackolf931 commented on AIS/AIS.API/ViewModels/QuestionSet/QuestionSetAddViewModel.cs
> +#nullable enable
fix

2022-03-18 11:13 UTC, Blackolf931 commented on AIS/AIS.BLL/Interfaces/Services/IQuestionSetService.cs
> +        Task<QuestionSet> Add(QuestionSet entity, CancellationToken ct);
fix

2022-03-18 11:13 UTC, Blackolf931 commented on AIS/AIS.BLL/Models/QuestionSet.cs
> +#nullable enable
fix

2022-03-18 11:14 UTC, Blackolf931 commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +            questionAreaIds.ForEach(x => _questionAreasQuestionSetsRepository.Add(
fix

2022-03-18 11:23 UTC, Blackolf931 commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +        private static List<int> ConvertToList(QuestionSet entity)
fix

2022-03-22 08:49 UTC, nantonov requested changes

2022-03-22 08:49 UTC, nantonov commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +                await _questionsQuestionSetsRepository.AddRange(questionsList.ToList(), ct);
ToList is redundant

2022-03-22 08:55 UTC, Blackolf931 commented on AIS/AIS.BLL/Services/QuestionSetService.cs
> +                await _questionsQuestionSetsRepository.AddRange(questionsList.ToList(), ct);
fix

2022-03-22 08:55 UTC, nantonov approved these changes

2022-03-22 08:55 UTC, merged