Feature/code review
nantonov/AIS pull request #77
Opened 2022-03-28 07:55 UTC by Blackolf931

2022-03-28 07:57 UTC, stas1408123 approved these changes

2022-03-28 08:06 UTC, GagarinPavel approved these changes

2022-03-29 08:05 UTC, Pyroti requested changes

2022-03-29 08:37 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionArea/components/questionAreaTableRow/QuestionAreaTableRow.tsx
fix

2022-03-29 08:37 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionArea/QuestionArea.tsx
> +}
fix

2022-03-29 08:37 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionAreaForm/QuestionAreaForm.tsx
>      }
fix

2022-03-29 08:37 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionAreaForm/QuestionAreaForm.tsx
>      };
fix

2022-03-29 08:37 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionSetDescription/QuestionSetDescription.tsx
> +}
fix

2022-03-29 08:42 UTC, Pyroti approved these changes

2022-03-29 08:42 UTC, merged