Feature/add eslint and prettier
nantonov/AIS pull request #82
Opened 2022-03-30 08:22 UTC by GagarinPavel

2022-03-30 08:34 UTC, stas1408123 approved these changes

2022-04-01 07:46 UTC, nantonov approved these changes

2022-04-01 09:08 UTC, Pyroti requested changes
у тебя во всех useEffect пропущены зависимости установи этот плагин и добавь настройки в eslint как тут написано
https://www.npmjs.com/package/eslint-plugin-react-hooks#installation

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionSetAdd/QuestionSetAdd.tsx
> +  };
здесь много повторяющегося кода есть смысл сделать один общий метод и третьим параметром передавать questionSetModel.questionAreaIds или questionSetModel.questionIds

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionSetAdd/QuestionSetAdd.tsx
> +  };
а еще объясни мне для чего они: questionSetModel.questionAreaIds и questionSetModel.questionIds

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionSetAdd/QuestionSetAdd.tsx
> +              onChange={(e) => changeQuestionHandler(index, Number(e.target.value))}
инлайн функция

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionSetAdd/QuestionSetAdd.tsx
>  `;
стили в компоненте это плохо

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionSetDescription/QuestionSetDescription.tsx
> +`;
стили

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionsSets/questionSetItem/QuestionSetItem.tsx
> +      }}
инлайн вызов

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionsSets/questionSetItem/QuestionSetItem.tsx
>  const QuestionSetNameText = styled.text``;
стили

2022-04-01 09:08 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionsSets/questionSetItem/QuestionSetItem.tsx
>  const QuestionSetNameText = styled.text``;
это что за тег такой text?

2022-04-04 12:11 UTC, Blackolf931 approved these changes

2022-04-04 12:12 UTC, Pyroti approved these changes

2022-04-04 12:12 UTC, merged