Feature/add question area pages
nantonov/AIS pull request #84
Opened 2022-04-04 12:50 UTC by GagarinPavel

2022-04-04 20:37 UTC, Pyroti requested changes

2022-04-04 20:37 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionAreaDescription/QuestionAreaDescription.tsx
> +    const path = `/questionSet/${changeId}`;
эта константа есть в mainRoutes, импорируй оттуда

2022-04-04 20:37 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionAreaDescription/QuestionAreaDescription.tsx
> +                      onClick={() => routeChangeSet(questionSet.id)}
инлайн вызов

2022-04-04 20:37 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionAreaDescription/QuestionAreaDescription.tsx
> +                      onClick={() => DeleteQuestionSet(Number(id), questionSet.id)}
инлайн вызов

2022-04-04 20:37 UTC, Pyroti commented on AIS.front/ais.front/src/pages/questionAreaForm/questionSetsForQuestionAreaForm/questionSetsForQuestionAreaForm.tsx
> +        Question sets:{' '}
{' '} - удалить

2022-04-05 06:00 UTC, Pyroti approved these changes

2022-04-05 07:38 UTC, nantonov approved these changes

2022-04-05 07:50 UTC, Blackolf931 approved these changes

2022-04-05 07:51 UTC, merged