Implement EmployeeController, EmployeeProfiles. Create Employee model…
nantonov/AIS pull request #9
Opened 2021-10-14 12:46 UTC by PaShkadun

…s. Connect services and repositories in configure.

2021-10-14 12:48 UTC, VadimZharikov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +            return _mapper.Map<EmployeeModel>(await _service.Add(_mapper.Map<EmployeeDto>(model)));
reafactor

2021-10-14 12:48 UTC, VadimZharikov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +            return _mapper.Map<EmployeeModel>(await _service.Put(_mapper.Map<EmployeeDto>(model)));
refactor

2021-10-14 12:49 UTC, VadimZharikov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +        [Route("delete")]
[HttpDelete("delete")] would be cleaner

2021-10-14 12:49 UTC, VadimZharikov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +        [Route("add")]
[HttpPost("add")]

2021-10-14 12:49 UTC, VadimZharikov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +        [Route("update")]
[HttpPut("update")]

2021-10-14 12:51 UTC, VadimZharikov commented on AIS/AIS.API/Startup.cs
> +            var mappingProfile = new MapperConfiguration(map =>
add assembly mapping profiles via DI

2021-10-14 12:52 UTC, VadimZharikov commented on AIS/AIS.API/Startup.cs
> +            services.AddSingleton(mapper);
you can add mapper via DI package

2021-10-14 12:54 UTC, nantonov commented on AIS/AIS.API/ViewModels/EmployeeModel.cs
> +    public class EmployeeModel
Rename as EmployeeViewModel

2021-10-14 12:54 UTC, nantonov commented on AIS/AIS.BLL/Models/EmployeeDto.cs
> +    public class EmployeeDto
Rename to Employee

2021-10-14 12:54 UTC, nantonov commented on AIS/AIS.BLL/Mappers/EmployeeDtoProfile.cs
> +    public class EmployeeDtoProfile : Profile
Get rid of DTO in name

2021-10-14 12:55 UTC, nantonov commented on AIS/AIS.DAL/Entities/Employee.cs
> +    public class Employee
Rename as EmployeeEntity

2021-10-15 06:51 UTC, nantonov requested changes

2021-10-15 06:51 UTC, nantonov commented on AIS/AIS.API/Controllers/EmployeeController.cs
> +        [HttpGet()]
Maybe without ()?

2021-10-15 06:51 UTC, nantonov commented on AIS/AIS.API/Startup.cs
> +            services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));
Why Repository is here?

2021-10-15 06:51 UTC, nantonov commented on AIS/AIS.API/Startup.cs
> +            services.AddScoped(typeof(IGenericService<>), typeof(GenericService<>));
Why Service is here?

2021-10-15 09:00 UTC, Blackolf931 approved these changes

2021-10-15 09:02 UTC, VadimZharikov approved these changes

2021-10-15 09:05 UTC, merged