Feature/refactoring add question set
nantonov/AIS pull request #90
Opened 2022-04-11 18:40 UTC by Blackolf931

2022-04-11 18:44 UTC, GagarinPavel approved these changes

2022-04-11 20:11 UTC, stas1408123 approved these changes

2022-04-12 11:00 UTC, Pyroti requested changes

2022-04-13 07:42 UTC, stas1408123 approved these changes

2022-04-13 09:03 UTC, Blackolf931 commented on AIS.front/ais.front/src/pages/questionsSets/style/BoxContainer.tsx
> +  width: 700,
doesn't work, i can't set this window on the center

2022-04-13 10:04 UTC, Pyroti approved these changes

2022-04-13 10:05 UTC, merged